# Generated by Django 4.2.16 on 2025-07-30 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='openai_api_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='youtube_api_key',
            field=models.CharField(max_length=255),
        ),
    ]
