# Generated by Django 4.2.16 on 2025-07-31 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userapikey_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
